//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAIApplication.Data.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTest
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TestId { get; set; }
        public int Score { get; set; }
        public string Time { get; set; }
        public int MaxScore { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
